### ISSUE TITLE
Make args_get require a capability

### ISSUE THREAD

**Issue by Ericson2314** [WebAssembly/wasi-classic-command#5]
https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-some-possible-changes.md#merging-read-and-recv recommends splitting things up, which is a good first step (code that doesn't depend on the environment part doesn't have that ambient authority). But going back to C's way is even better, where `main` is responsible for handing out access to the arguments. [I think rust's `std` made a mistake in doing something more like what the wasmtime first draft has now.]

**Comment by sunfishcode** [comment]
The new plan here is to make command-line arguments be arguments to the command entrypoint function, which turns out to be what the original comment in this issue suggested. Follow https://github.com/WebAssembly/WASI/issues/509 going forward.
